### ISSUE TITLE
fork required

### ISSUE THREAD

**Issue by dwijnand** [ensime/pcplod#12] opened 2016-09-13 15:08 UTC
## steps

**project/build.properties**
```ini
sbt.version=0.13.12
```

**build.sbt**
```scala
val pcno = project in file(".")

scalaVersion := "2.11.8"

libraryDependencies += "org.ensime"     %% "pcplod"         % "1.0.0" % "test"
dependencyOverrides += "org.scala-lang"  % "scala-compiler" % scalaVersion.value
```

**src/test/scala/MacroTest.scala**
```scala
package pcno

import org.ensime.pcplod._

object MacroTest {
  def main(args: Array[String]): Unit = {
    withMrPlod("O.scala") { mr =>
      assert(mr.messages.isEmpty)
    }
  }
}
```

**src/test/resources/O.scala**
```scala
object O
```

Run:
```bash
$ sbt
> test:run
```

## problem

```
[info] Running pcno.MacroTest
[error] (run-main-2) scala.reflect.internal.FatalError: package scala does not have a member Int
scala.reflect.internal.FatalError: package scala does not have a member Int
       	at scala.reflect.internal.Definitions$DefinitionsClass.scala$reflect$internal$Definitions$DefinitionsClass$$fatalMissingSymbol(Definitions.scala:1186)
       	at scala.reflect.internal.Definitions$DefinitionsClass.getMember(Definitions.scala:1203)
       	at scala.reflect.internal.Definitions$ValueClassDefinitions$class.valueClassSymbol(Definitions.scala:77)
       	at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntClass(Definitions.scala:114)
       	at scala.reflect.internal.Definitions$DefinitionsClass.IntClass$lzycompute(Definitions.scala:153)
       	at scala.reflect.internal.Definitions$DefinitionsClass.IntClass(Definitions.scala:153)
       	at scala.reflect.internal.Definitions$ValueClassDefinitions$class.IntTpe(Definitions.scala:127)
       	at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe$lzycompute(Definitions.scala:153)
       	at scala.reflect.internal.Definitions$DefinitionsClass.IntTpe(Definitions.scala:153)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:630)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:728)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:774)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getType(ClassfileParser.scala:289)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:568)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$queueLoad$1(ClassfileParser.scala:483)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser$$anonfun$parseClass$1.apply$mcV$sp(ClassfileParser.scala:493)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:498)
       	at scala.tools.nsc.symtab.classfile.ClassfileParser.parse(ClassfileParser.scala:139)
       	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply$mcV$sp(SymbolLoaders.scala:347)
       	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
       	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader$$anonfun$doComplete$2.apply(SymbolLoaders.scala:347)
       	at scala.reflect.internal.SymbolTable.enteringPhase(SymbolTable.scala:235)
       	at scala.tools.nsc.symtab.SymbolLoaders$ClassfileLoader.doComplete(SymbolLoaders.scala:347)
       	at scala.tools.nsc.symtab.SymbolLoaders$SymbolLoader.complete(SymbolLoaders.scala:211)
       	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1514)
       	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1659)
       	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
       	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
       	at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1320)
       	at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1343)
       	at scala.tools.nsc.interactive.Global.<init>(Global.scala:299)
       	at org.ensime.pcplod.PoshPresentationCompiler.<init>(PoshPresentationCompiler.scala:46)
       	at org.ensime.pcplod.PoshPresentationCompiler$.create(PoshPresentationCompiler.scala:39)
       	at org.ensime.pcplod.PcPlod.<init>(PcPlod.scala:43)
       	at org.ensime.pcplod.PcPlod$.apply(PcPlod.scala:11)
       	at org.ensime.pcplod.MrPlod$.apply(PcPlod.scala:137)
       	at org.ensime.pcplod.package$.withMrPlod(package.scala:16)
       	at pcno.MacroTest$.main(MacroTest.scala:7)
       	at pcno.MacroTest.main(MacroTest.scala)
```

## expectation

The compiler doesn't blow up.

**Comment by fommil** [comment] 2016-09-14 10:37
believe it or not, I think this is a dupe of the classpath ticket.

**Comment by dwijnand** [comment] 2016-09-14 10:40
Which ticket?

**Comment by fommil** [comment] 2016-09-14 10:46
try this for the latest branch

```
val pcno = project in file(".")

scalaVersion := "2.11.8"

libraryDependencies += "org.ensime"     %% "pcplod"         % "1.1.0-SNAPSHOT" % "test"
dependencyOverrides += "org.scala-lang"  % "scala-compiler" % scalaVersion.value

javaOptions in Test ++= Seq(
  s"""-Dpcplod.settings=${(scalacOptions in Test).value.mkString(",")}""",
  s"""-Dpcplod.classpath=${(fullClasspath in Test).value.map(_.data).mkString(",")}"""
)

fork := true

```

**Comment by dwijnand** [comment] 2016-09-14 11:02
`fork := true` is sufficient.

This seems relevant: https://github.com/sbt/sbt/pull/935/files#diff-73448299b8e2ad66f175bd874941aa40R259

**Comment by fommil** [comment] 2016-09-14 11:05
cool, closing as WontFix

**Closed by fommil** 2016-09-14 11:05 UTC
Labels: bug

**Comment by dwijnand** [comment] 2016-09-14 11:12
Documented in the README: https://github.com/ensime/pcplod/commit/4959f26c9a0a0a8638b65d023cd6c97b4555e846
